### ISSUE TITLE
leave out one var

### ISSUE THREAD

**Issue by ismferd** [wimpy/wimpy.deploy#1]
Hi,
(this is not Issue is more a question)
Why do you use 2 vars?
- wimpy_aws_elb_vpc_subnets: ["subnet-asd234sa", "subnet-bcfg234sa"]
- wimpy_aws_asg_vpc_subnets: ["subnet-asd234sa", "subnet-bcfg234sa"]

I think that the elb subnets and asg subnets will be always the same.

What do you think?

**Comment by fiunchinho** [comment]
If you think they will always be the same, we can use only one of the variables and remove the other one. It's simpler!

**Comment by fiunchinho** [comment]
Added variable wimpy_vpc_subnets so it's simpler to use
